name: Docker Image CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build -f docker/Dockerfile --tag hollingsworthsteven/jira-freeplane:${GITHUB_REF_NAME} .
          # docker push hollingsworthsteven/jira-freeplane:${GITHUB_REF_NAME}
